# Settings that the LAMMPS build will import when this package library is used
  
ifneq (,$(findstring mpi_stubs,$(MPI_LIB)))
   user-mist_SYSINC =
else
   user-mist_SYSINC = -D__MIST_WITH_MPI
endif

user-mist_SYSLIB =
user-mist_SYSPATH =
